import './globals.css'
import type { Metadata } from 'next'
import { Karla } from 'next/font/google'

const font = Karla({ subsets: ['latin'], weight: ['400', '700'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${font.className} bg-light_gray text-base`}>
        {children}
      </body>
    </html>
  )
}
